-- MySQL Script generated by MySQL Workbench
-- Mon Nov 23 01:08:33 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema datafit_android
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema datafit_android
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `datafit_android` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `datafit_android` ;

-- -----------------------------------------------------
-- Table `datafit_android`.`gcm_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datafit_android`.`gcm_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gcm_regid` TEXT,
  `name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;